// Placeholder local data for static UI; replace with real API wiring in a follow-up package.
type PartOfSpeech = "noun" | "verb" | "adjective" | "phrase";

function mockWord(
  term: string,
  wordSlug: string,
  meaning: string,
  partOfSpeech: PartOfSpeech,
  example: string,
  collocation: string,
  register: string,
  commonMistake: string,
  isSaved: boolean,
) {
  return {
    term,
    wordSlug,
    meaning,
    meanings: [{ partOfSpeech, definition: meaning }],
    examples: [example],
    usageNotes: { collocation, register, commonMistake },
    isSaved,
  } as const;
}

export const MOCK_SITUATION_WORD_LISTS = {
  airport: {
    title: "Airport",
    words: [
      mockWord(
        "boarding pass",
        "boarding-pass",
        "A document that lets you get on your flight.",
        "noun",
        "Please have your boarding pass ready at the gate.",
        "show a boarding pass",
        "Neutral; standard travel vocabulary.",
        "Do not confuse a boarding pass with a ticket, which confirms the booking.",
        true,
      ),
      mockWord(
        "gate",
        "gate",
        "The place where you board your plane.",
        "noun",
        "Our flight leaves from gate twelve.",
        "departure gate",
        "Neutral; standard travel vocabulary.",
        "At an airport, a gate is a boarding area, not only a physical door.",
        false,
      ),
      mockWord(
        "security check",
        "security-check",
        "The screening process before entering the departure area.",
        "noun",
        "We arrived early to allow time for the security check.",
        "go through a security check",
        "Neutral; standard travel vocabulary.",
        "Say go through security, not pass from security.",
        false,
      ),
      mockWord(
        "luggage",
        "luggage",
        "Bags and suitcases you take on a trip.",
        "noun",
        "Her luggage is already on the plane.",
        "check in luggage",
        "Neutral; baggage is a common synonym.",
        "Luggage is uncountable; say two pieces of luggage, not two luggages.",
        true,
      ),
      mockWord(
        "customs",
        "customs",
        "A border check for goods.",
        "noun",
        "We went through customs after collecting our bags.",
        "go through customs",
        "Neutral; standard border-control vocabulary.",
        "Customs takes a singular verb when it names the government service.",
        false,
      ),
      mockWord(
        "layover",
        "layover",
        "A stop between flights.",
        "noun",
        "We have a three-hour layover in Madrid.",
        "a short layover",
        "Neutral; stopover is also common.",
        "A layover is between connecting flights, not the final destination.",
        false,
      ),
    ],
  },
  restaurant: {
    title: "Restaurant",
    words: [
      mockWord(
        "menu",
        "menu",
        "A list of food and drinks you can order.",
        "noun",
        "Could we see the menu, please?",
        "read the menu",
        "Neutral; standard restaurant vocabulary.",
        "Menu refers to the list, not usually the individual meal ordered.",
        true,
      ),
      mockWord(
        "reservation",
        "reservation",
        "A booking for a table.",
        "noun",
        "I made a reservation for seven o'clock.",
        "make a reservation",
        "Neutral; booking is also common.",
        "Use a reservation for the booking and reserve for the verb.",
        false,
      ),
      mockWord(
        "appetizer",
        "appetizer",
        "A small dish eaten before the main meal.",
        "noun",
        "We shared an appetizer before dinner.",
        "order an appetizer",
        "Common in American English; starter is common in British English.",
        "An appetizer comes before the main course, not after it.",
        false,
      ),
      mockWord(
        "bill",
        "bill",
        "The statement showing how much you need to pay.",
        "noun",
        "Could we have the bill, please?",
        "ask for the bill",
        "Neutral; check is common in American restaurants.",
        "Do not use receipt when asking how much you owe; the receipt comes after payment.",
        true,
      ),
      mockWord(
        "tip",
        "tip",
        "Extra money given to thank someone for service.",
        "noun",
        "We left a tip for the server.",
        "leave a tip",
        "Neutral; tipping customs vary by place.",
        "A tip is extra money, while the bill is the amount charged.",
        false,
      ),
      mockWord(
        "take-out",
        "take-out",
        "Food to eat somewhere else.",
        "noun",
        "We ordered take-out after work.",
        "order take-out",
        "Informal; takeaway is common in British English.",
        "As a noun use take-out; the verb phrase is take out.",
        false,
      ),
    ],
  },
  "hotel-check-in": {
    title: "Hotel Check-in",
    words: [
      mockWord(
        "reservation",
        "reservation",
        "A booking for a room at a hotel.",
        "noun",
        "The receptionist found our reservation.",
        "confirm a reservation",
        "Neutral; standard hotel vocabulary.",
        "Use reservation for the booking and reserve for the action.",
        true,
      ),
      mockWord(
        "front desk",
        "front-desk",
        "The hotel counter for guest help.",
        "noun",
        "Please collect your key at the front desk.",
        "call the front desk",
        "Neutral; reception is a common synonym.",
        "Front desk names the service area, not the desk in a guest room.",
        false,
      ),
      mockWord(
        "key card",
        "key-card",
        "An electronic card used to open your room.",
        "noun",
        "My key card stopped working.",
        "activate a key card",
        "Neutral; standard hotel vocabulary.",
        "Write key card as two words when it is a noun.",
        false,
      ),
      mockWord(
        "amenities",
        "amenities",
        "Useful hotel services or features.",
        "noun",
        "The hotel amenities include a gym and a pool.",
        "hotel amenities",
        "Neutral; common in travel descriptions.",
        "Amenities are useful features, not basic room furniture in general.",
        true,
      ),
      mockWord(
        "wake-up call",
        "wake-up-call",
        "A scheduled phone call to wake you up.",
        "noun",
        "I requested a wake-up call for six thirty.",
        "request a wake-up call",
        "Neutral; standard hotel vocabulary.",
        "Use wake-up with a hyphen before call; wake up is the verb phrase.",
        false,
      ),
      mockWord(
        "check-out",
        "check-out",
        "The process of leaving a hotel.",
        "noun",
        "Check-out is at eleven in the morning.",
        "late check-out",
        "Neutral; standard hotel vocabulary.",
        "Use check-out for the noun and check out for the verb.",
        false,
      ),
    ],
  },
  "job-interview": {
    title: "Job Interview",
    words: [
      mockWord(
        "resume",
        "resume",
        "A summary of your work experience and skills.",
        "noun",
        "Bring a copy of your resume to the interview.",
        "update a resume",
        "Neutral; CV is used in many regions.",
        "Resume without accents can also mean continue, so context matters.",
        true,
      ),
      mockWord(
        "qualifications",
        "qualifications",
        "Skills and experience for a job.",
        "noun",
        "Her qualifications match the role.",
        "meet the qualifications",
        "Neutral; standard employment vocabulary.",
        "Qualifications are evidence of suitability, not only academic degrees.",
        false,
      ),
      mockWord(
        "references",
        "references",
        "People who can speak about your work.",
        "noun",
        "The employer asked for two references.",
        "provide references",
        "Neutral; standard employment vocabulary.",
        "A reference may mean the person or their recommendation; make the context clear.",
        false,
      ),
      mockWord(
        "salary expectations",
        "salary-expectations",
        "The pay range you hope to receive.",
        "phrase",
        "The recruiter asked about my salary expectations.",
        "discuss salary expectations",
        "Neutral; common in recruitment.",
        "Use the plural expectations in this standard interview phrase.",
        true,
      ),
      mockWord(
        "cover letter",
        "cover-letter",
        "A letter for a job application.",
        "noun",
        "I tailored my cover letter to the position.",
        "write a cover letter",
        "Neutral; standard employment vocabulary.",
        "A cover letter supports a resume; it does not replace it.",
        false,
      ),
      mockWord(
        "follow-up",
        "follow-up",
        "A message sent after an interview.",
        "noun",
        "She sent a follow-up the next morning.",
        "send a follow-up",
        "Neutral; common business vocabulary.",
        "Use follow-up for the noun and follow up for the verb.",
        false,
      ),
    ],
  },
  "daily-conversation": {
    title: "Daily Conversation",
    words: [
      mockWord(
        "small talk",
        "small-talk",
        "Light conversation about everyday topics.",
        "noun",
        "We made small talk while waiting.",
        "make small talk",
        "Neutral to informal.",
        "Small talk is uncountable; do not say a small talk for one conversation.",
        true,
      ),
      mockWord(
        "catch up",
        "catch-up",
        "To talk after time apart.",
        "verb",
        "Let's catch up over coffee.",
        "catch up with someone",
        "Informal and friendly.",
        "Use catch up as the verb; catch-up is the noun or adjective.",
        false,
      ),
      mockWord(
        "weekend plans",
        "weekend-plans",
        "Activities planned for the weekend.",
        "phrase",
        "Do you have any weekend plans?",
        "make weekend plans",
        "Neutral and conversational.",
        "Use plans in the plural when asking generally about someone's weekend.",
        false,
      ),
      mockWord(
        "greeting",
        "greeting",
        "Words used to say hello to someone.",
        "noun",
        "She opened the email with a friendly greeting.",
        "exchange greetings",
        "Neutral; the exact greeting may be formal or informal.",
        "Greeting is the noun; greet is the verb.",
        true,
      ),
      mockWord(
        "farewell",
        "farewell",
        "Words used to say goodbye to someone.",
        "noun",
        "They said a quick farewell at the station.",
        "say farewell",
        "Neutral to formal; goodbye is more conversational.",
        "Farewell can sound formal, so use goodbye in casual speech when appropriate.",
        false,
      ),
      mockWord(
        "casual",
        "casual",
        "Relaxed and informal in style or conversation.",
        "adjective",
        "The conversation was friendly and casual.",
        "casual conversation",
        "Informal in tone but neutral as a description.",
        "Casual describes a noun; casually is the adverb.",
        false,
      ),
    ],
  },
  "work-meeting": {
    title: "Work Meeting",
    words: [
      mockWord(
        "agenda",
        "agenda",
        "A list of topics planned for a meeting.",
        "noun",
        "The budget is first on today's agenda.",
        "set the agenda",
        "Neutral; standard workplace vocabulary.",
        "Agenda is singular in modern English; agendas is the plural.",
        true,
      ),
      mockWord(
        "action items",
        "action-items",
        "Tasks assigned after a meeting.",
        "noun",
        "We reviewed the action items before leaving.",
        "assign action items",
        "Neutral; common workplace vocabulary.",
        "Action items are specific tasks, not all topics discussed.",
        false,
      ),
      mockWord(
        "deadline",
        "deadline",
        "The latest time something must be finished.",
        "noun",
        "The deadline is Friday afternoon.",
        "meet a deadline",
        "Neutral; standard workplace vocabulary.",
        "You meet a deadline when on time and miss it when late.",
        false,
      ),
      mockWord(
        "follow-up",
        "follow-up",
        "A later message or action.",
        "noun",
        "The manager scheduled a follow-up for Monday.",
        "a follow-up meeting",
        "Neutral; common business vocabulary.",
        "Use follow-up for the noun or adjective and follow up for the verb.",
        true,
      ),
      mockWord(
        "stakeholder",
        "stakeholder",
        "A person interested in a project.",
        "noun",
        "We invited each stakeholder to comment.",
        "key stakeholder",
        "Neutral; common business vocabulary.",
        "A stakeholder can be affected by a project without owning company shares.",
        false,
      ),
      mockWord(
        "brainstorm",
        "brainstorm",
        "To share ideas freely to solve a problem.",
        "verb",
        "Let's brainstorm possible names for the product.",
        "brainstorm ideas",
        "Neutral to informal workplace language.",
        "Brainstorm can take a direct object; brainstorm about is often unnecessary.",
        false,
      ),
    ],
  },
  "university-class": {
    title: "University Class",
    words: [
      mockWord(
        "lecture",
        "lecture",
        "A lesson given by an instructor to a class.",
        "noun",
        "Today's lecture covers climate policy.",
        "attend a lecture",
        "Neutral; standard academic vocabulary.",
        "A lecture is the teaching session, while a lecturer is the person.",
        true,
      ),
      mockWord(
        "assignment",
        "assignment",
        "Work a teacher asks students to complete.",
        "noun",
        "The assignment is due next week.",
        "complete an assignment",
        "Neutral; standard academic vocabulary.",
        "Assignment is countable; homework is usually uncountable.",
        false,
      ),
      mockWord(
        "syllabus",
        "syllabus",
        "A document describing a course.",
        "noun",
        "The reading list is in the syllabus.",
        "course syllabus",
        "Neutral; standard academic vocabulary.",
        "The common plurals are syllabuses and syllabi.",
        false,
      ),
      mockWord(
        "office hours",
        "office-hours",
        "Times to meet an instructor.",
        "noun",
        "I asked the professor a question during office hours.",
        "hold office hours",
        "Neutral; standard academic vocabulary.",
        "Office hours is normally plural even when referring to a recurring period.",
        true,
      ),
      mockWord(
        "group project",
        "group-project",
        "An assignment with other students.",
        "noun",
        "Our group project includes a presentation.",
        "work on a group project",
        "Neutral; standard academic vocabulary.",
        "A group project is collaborative; an individual project is completed alone.",
        false,
      ),
      mockWord(
        "deadline",
        "deadline",
        "When work must be submitted.",
        "noun",
        "The essay deadline is at noon.",
        "submission deadline",
        "Neutral; standard academic vocabulary.",
        "Use by before a deadline time, not until when stating the required submission time.",
        false,
      ),
    ],
  },
} as const;

export type SituationSlug = keyof typeof MOCK_SITUATION_WORD_LISTS;
